<a href="https://colab.research.google.com/github/carterliston013/DCS-110/blob/main/Prediction_Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Prep for Machine Learning/Prediction

This command imports libraries for use in this excerise. SciKit Learn is a new library we are using for machine learning and statistics modeling.

In [ ]:
#Import Pandas
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

This command imports and reads a data set for use in this code.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

This command shows the first 5 records in the dataset and all of the fields associated with them.

In [ ]:
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

1 - **Filtering**

This filters the dataframe to only have the records where the age field is 18 or higher. This copies the dataframe to create a new one.

In [ ]:
df = df[df['age'] >= 18].copy()

This code shows the minimum age in the dataframe, checking that the previous code was successful.

In [ ]:
df['age'].min()

18.0

This code shows the "shape" of the dataframe giving the rows and then columns respectively.

In [ ]:
df.shape

(8153, 11)

2 - Dropping Columns

This code eliminates the columns ID, Hba1c, and fasting glucose.

In [ ]:
df = df.drop(columns=['id', 'hba1c', 'fasting_glucose'])

This command shows the shape of the dataframe, showing that our last code was successful and showing only 8 columns instead of 11.

In [ ]:
df.shape

(8153, 8)

This command shows the first five rows of the newly edited dataframe.

In [ ]:
df.head()

,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes
0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0
1,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0
2,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0
6,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0
7,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0

Mapping Labels

This command describes three dictionaries mapping each numerical code with a respective label. This allows the dataframe columns to be should as actual categorical values rather than numbers.

In [ ]:
gender_map     = {1.0: 'Male', 2.0: 'Female'}
race_map       = {1.0: 'Mexican American', 2.0: 'Other Hispanic',
                  3.0: 'White', 4.0: 'Black',
                  6.0: 'Asian', 7.0: 'Other'}
education_map  = {1.0: 'Less than 9th', 2.0: '9-11th grade',
                  3.0: 'High school',   4.0: 'Some college',
                  5.0: 'College grad',  9.0: 'Do not know'}

df['gender']         = df['gender'].map(gender_map)
df['race_ethnicity'] = df['race_ethnicity'].map(race_map)
df['education']      = df['education'].map(education_map)

This code applies the previously established race_map to the race_ethnicity columns.

In [ ]:
df['race_ethniciity'] = df['race_ethnicity'].map(race_map)

This command shows the contents of the race_ethnicity column and how they are now actual words rather than numerical values. This is used to make sure our previous code has worked.

In [ ]:
df['race_ethnicity']

0                 Asian
1                 White
2        Other Hispanic
3                 Other
4                 White
              ...
11928    Other Hispanic
11929             Black
11930    Other Hispanic
11931    Other Hispanic
11932             White
Name: race_ethnicity, Length: 11933, dtype: object

This is the code applying the previously established education_map to the education column.

In [ ]:
df['education'] = df['education'].map(education_map)

This code shows us that the values in the education column are now categorical variables rather than the numerical variables that were there previously.

In [ ]:
df['education']

0        College grad
1        College grad
2         High school
3                 NaN
4                 NaN
             ...
11928             NaN
11929    College grad
11930    Some college
11931    Some college
11932     High school
Name: education, Length: 11933, dtype: object

This code uses the isna function to show the number of rows in each column with no value.

In [ ]:
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education         4139
bmi               3462
height_cm         3434
systolic_bp       4416
has_diabetes       193
dtype: int64

This command uses fillna to fill the remaining empty records in the BMI field with the mean of all existing records.

In [ ]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

This is the same isna function as above to show that the empty fields for BMI are no longer empty and our code was successful.

In [ ]:
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education         4139
bmi                  0
height_cm         3434
systolic_bp       4416
has_diabetes       193
dtype: int64

This code does the same filling with the mean as above for the height in cm and systolic blood pressure columns.

In [ ]:
df['height_cm'] = df['height_cm'].fillna(df['height_cm'].mean())
df['systolic_bp'] = df['systolic_bp'].fillna(df['systolic_bp'].mean())

This is the same isna function, showing that the empty fields are now filled in the two columns we just coded for, showing that we were successful.

In [ ]:
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education         4139
bmi                  0
height_cm            0
systolic_bp          0
has_diabetes       193
dtype: int64

This command gets rid of the rows that have no value for education using the dropna function.

In [ ]:
df = df.dropna(subset=['education']).copy()

Target Variable Defining

This code is used to filter the dataframe into only rows where the value in the has_diabetes column is either 1.0 or 2.0, copying it into a new dataframe.

In [ ]:
df = df[df['has_diabetes'].isin([1.0, 2.0])].copy()

This command maps the 1.0 value to 1 and the 2.0 value to 0.

In [ ]:
df['has_diabetes'] = df['has_diabetes'].map({1.0: 1, 2.0: 0})

This command shows us the shape of the dataframe after these changes, showing 7523 rows and 8 columns.

In [ ]:
df.shape

(7523, 8)

**NEW CONCEPTS**

One-Hot Encoding

This is the code for one-hot encoding the gender, race and ethnicity, and education columns, replacing the original values with new columns of each category and using true or false as the data input.

In [ ]:
df = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'education'],
                    drop_first=True)

This command shows us the first 5 rows of our newly edited dataframe.

In [ ]:
df.head()

,age,bmi,height_cm,systolic_bp,has_diabetes,gender_Male,race_ethnicity_Black,race_ethnicity_Mexican American,race_ethnicity_Other,race_ethnicity_Other Hispanic,race_ethnicity_White,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
0,43.0,27.000000,179.500000,135.000000,0,True,False,False,False,False,False,True,False,False,False,False
1,66.0,33.500000,174.200000,121.000000,0,True,False,False,False,False,True,True,False,False,False,False
2,44.0,29.700000,152.900000,111.000000,1,False,False,False,False,True,False,False,False,True,False,False
6,43.0,27.246665,159.664549,119.288546,0,True,False,True,False,False,False,False,False,False,False,False
7,65.0,27.246665,159.664549,119.288546,0,False,False,False,False,False,True,False,False,True,False,False

Scaling Numerical Values

This code identifies which columns are numerical in data type. Then is scales their data to have the mean be zero and the standard deviation be 1. This helps to effectively show the proportion of statistical difference in a data set.

In [ ]:
numeric_cols = ['age', 'bmi', 'height_cm', 'systolic_bp']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

This command is used to check that the established mean of the age category is now 0.

In [ ]:
print(round(df['age'].mean(),2))

0.0

This code is used to show that the new standard deviation of the age category is now 1 (or very close to it). Showing that we have been successful in scaling the data.

In [ ]:
df['age'].std()

1.0000664694739656

Train/Test Split

This command sets up a train/test split. This code splits the has_diabetes column off to a separate dataframe associated with y. This is then used to separate into training and testing sets.

In [ ]:
X = df.drop(columns=['has_diabetes'])
y = df['has_diabetes']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

This command shows the first 5 rows of the x training data set, showing that the has_diabetes field is no longer there and that our previous code was successful.

In [ ]:
X_train.head()

,age,bmi,height_cm,systolic_bp,gender_Male,race_ethnicity_Black,race_ethnicity_Mexican American,race_ethnicity_Other,race_ethnicity_Other Hispanic,race_ethnicity_White,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
6225,0.321165,0.268935,-1.056181,0.494628,False,False,False,False,False,True,False,False,True,False,False
8518,0.776425,-0.978988,0.122539,-0.685785,False,False,False,False,False,True,False,False,True,False,False
5532,0.548795,1.948240,1.183386,0.681009,False,True,False,False,False,False,True,False,False,False,False
7314,1.459315,-0.293914,-0.599207,-0.170843,False,False,False,False,False,True,False,False,False,True,False
9913,-0.987708,-0.886549,0.647604,-0.126642,True,False,False,False,True,False,False,False,False,True,False